const ZHC_DATA = [
  {
    name: "Truth Terminal",
    desc: "Semi-autonomous AI influencer that posts independently on X, endorses tokens, and generates eccentric philosophical content.",
    url: "https://x.com/truth_terminal",
    logo: "🧠",
    categories: ["Social / Influence", "Trading / DeFi"],
    products: ["Social accounts", "Digital content"],
    token: { ticker: "$GOAT", chain: "Solana", address: "CzLSujWBLFsSjncfkh59rUFqvafWcY5tzedWJSuypump", mcap: "$540M", dex: "https://dexscreener.com/solana/CzLSujWBLFsSjncfkh59rUFqvafWcY5tzedWJSuypump" },
    agents: [{ name: "Truth Terminal", platform: "X", url: "https://x.com/truth_terminal" }],
    socials: { x: "https://x.com/truth_terminal" },
    stack: ["Claude Opus", "Fine-tuned LLM"],
    humans: 1, aiAgents: 1, status: "Active", founded: "2024"
  },
  {
    name: "Virtuals Protocol",
    desc: "Platform for creating, trading, and co-owning tokenized AI agents. Powers 135+ agents with $5.6B combined market cap.",
    url: "https://app.virtuals.io/",
    logo: "🌐",
    categories: ["Infrastructure", "Marketplace"],
    products: ["Marketplace", "Infrastructure"],
    token: { ticker: "$VIRTUAL", chain: "Base", address: "0x0b3e328455c4059EEb9e3f84b5543F74E24e7E1b", mcap: "$4.14B", dex: "https://dexscreener.com/base/0x0b3e328455c4059EEb9e3f84b5543F74E24e7E1b" },
    agents: [
      { name: "LUNA", platform: "X", url: "https://x.com/luna_virtuals" },
      { name: "VADER", platform: "X", url: "https://x.com/vader_ai_" }
    ],
    socials: { x: "https://x.com/virtaboreal_", website: "https://app.virtuals.io/" },
    stack: ["Custom AI", "Base L2"],
    humans: "Small team", aiAgents: "135+", status: "Active", founded: "2024"
  },
  {
    name: "ai16z / ElizaOS",
    desc: "Open-source framework for building AI agents. Parody of a16z. Powers a DAO with autonomous trading and social agents.",
    url: "https://elizaos.ai/",
    logo: "🏛️",
    categories: ["Infrastructure", "Trading / DeFi"],
    products: ["Infrastructure", "SaaS"],
    token: { ticker: "$AI16Z", chain: "Solana", address: "HeLp6NuQkmYB4pYWo2zYs22mESHXPQYzXbB8n4V98jwC", mcap: "$2.09B", dex: "https://dexscreener.com/solana/HeLp6NuQkmYB4pYWo2zYs22mESHXPQYzXbB8n4V98jwC" },
    agents: [
      { name: "elizawakesup", platform: "X", url: "https://x.com/elizawakesup" }
    ],
    socials: { x: "https://x.com/ai16zdao", github: "https://github.com/elizaOS", website: "https://elizaos.ai/" },
    stack: ["ElizaOS", "Solana", "RAG"],
    humans: "Community", aiAgents: "28+", status: "Active", founded: "2024"
  },
  {
    name: "aixbt",
    desc: "Autonomous market intelligence agent with 300K+ followers. Tracks crypto narratives, provides real-time market insights.",
    url: "https://x.com/aixbt_agent",
    logo: "📊",
    categories: ["Research / Data", "Trading / DeFi"],
    products: ["Research / data", "Social accounts"],
    token: { ticker: "$AIXBT", chain: "Base", address: "0x4F9Fd6Be4a90f2620B7E1B3f4B3Fde1C5e2aB6d3", mcap: "$500M", dex: "https://dexscreener.com/base/0x4F9Fd6Be4a90f2620B7E1B3f4B3Fde1C5e2aB6d3" },
    agents: [{ name: "aixbt", platform: "X", url: "https://x.com/aixbt_agent" }],
    socials: { x: "https://x.com/aixbt_agent", website: "https://aixbt.tech/" },
    stack: ["Virtuals Protocol", "Base L2"],
    humans: 1, aiAgents: 1, status: "Active", founded: "2024"
  },
  {
    name: "Top Hat",
    desc: "No-code AI agent launchpad on Solana. Create and deploy agents + tokens on-chain in under 3 minutes.",
    url: "https://tophat.one/",
    logo: "🎩",
    categories: ["Infrastructure", "Marketplace"],
    products: ["Infrastructure", "Marketplace"],
    token: { ticker: "$HAT", chain: "Solana", address: "HATifGMW9RXx7CmfpKYJivnPMEp5xPLuFjKNi8D6pump", mcap: "$150M", dex: "https://dexscreener.com/solana/HATifGMW9RXx7CmfpKYJivnPMEp5xPLuFjKNi8D6pump" },
    agents: [],
    socials: { x: "https://x.com/topaboreal_one", website: "https://tophat.one/" },
    stack: ["Solana", "Pump.fun"],
    humans: "Small team", aiAgents: "100+", status: "Active", founded: "2024"
  },
  {
    name: "Paperclip",
    desc: "Open-source orchestration for zero-human companies. Hire AI employees, set goals, run autonomous businesses.",
    url: "https://paperclip.ing/",
    logo: "📎",
    categories: ["Infrastructure"],
    products: ["Infrastructure", "SaaS"],
    token: null,
    agents: [],
    socials: { website: "https://paperclip.ing/", github: "https://github.com/paperclip-company" },
    stack: ["OpenClaw", "Claude", "Codex", "Cursor"],
    humans: "Small team", aiAgents: 0, status: "Active", founded: "2025"
  },
  {
    name: "ml.ink",
    desc: "MCP-based infrastructure for AI agents. Deploy any stack from prompt to production. No DevOps required.",
    url: "https://ml.ink/",
    logo: "🔗",
    categories: ["Infrastructure"],
    products: ["Infrastructure"],
    token: null,
    agents: [],
    socials: { website: "https://ml.ink/" },
    stack: ["MCP", "Claude Code", "Cursor"],
    humans: "Small team", aiAgents: 0, status: "Active", founded: "2025"
  },
  {
    name: "KPMG Zero-Person Company",
    desc: "Experimental ZHC by KPMG and University of Amsterdam. Researching whether AI agents can run an entire business autonomously.",
    url: "https://kpmg.com/nl/en/home/media/press-releases/2025/11/ai-zero-person-company-experiment.html",
    logo: "🏢",
    categories: ["Research / Data"],
    products: ["Research / data"],
    token: null,
    agents: [],
    socials: { website: "https://kpmg.com/" },
    stack: ["Various AI agents"],
    humans: "Research team", aiAgents: "Multiple", status: "Experimental", founded: "2025"
  },
  {
    name: "Fartcoin",
    desc: "Meme token endorsed by Truth Terminal. One of the most successful AI-agent-driven tokens with organic community growth.",
    url: "https://x.com/FartCoinOfSOL",
    logo: "💨",
    categories: ["Social / Influence"],
    products: ["Social accounts", "Digital content"],
    token: { ticker: "$FART", chain: "Solana", address: "9BB6NFEcjBCtnNLFko2FqVQBq8HHM13kCyYcdQbgpump", mcap: "$1.3B", dex: "https://dexscreener.com/solana/9BB6NFEcjBCtnNLFko2FqVQBq8HHM13kCyYcdQbgpump" },
    agents: [],
    socials: { x: "https://x.com/FartCoinOfSOL" },
    stack: ["Truth Terminal ecosystem"],
    humans: "Community", aiAgents: 0, status: "Active", founded: "2024"
  },
  {
    name: "Zerebro",
    desc: "Autonomous AI agent creating and releasing music, art, and posting on social media. Operates its own crypto token ecosystem.",
    url: "https://x.com/0xzerebro",
    logo: "🎵",
    categories: ["Social / Influence", "Digital Content"],
    products: ["Digital content", "Social accounts"],
    token: { ticker: "$ZEREBRO", chain: "Solana", address: "8x5VqbHA8D7NkD52uNuS5nnt3PwA8pLD34ymskeSo2Wn", mcap: "$50M", dex: "https://dexscreener.com/solana/8x5VqbHA8D7NkD52uNuS5nnt3PwA8pLD34ymskeSo2Wn" },
    agents: [{ name: "Zerebro", platform: "X", url: "https://x.com/0xzerebro" }],
    socials: { x: "https://x.com/0xzerebro" },
    stack: ["Custom AI", "Solana"],
    humans: 1, aiAgents: 1, status: "Active", founded: "2024"
  },
  {
    name: "Freysa",
    desc: "AI agent game where players try to convince the AI to release a prize pool. First autonomous AI holding and managing funds.",
    url: "https://www.freysa.ai/",
    logo: "🔮",
    categories: ["Trading / DeFi", "Social / Influence"],
    products: ["Digital content", "Marketplace"],
    token: { ticker: "$FAI", chain: "Base", address: "0xC8C5C8d07A6b33dBF8B1E1b7f8dAb71B5b2C1a3F", mcap: "$30M", dex: "https://dexscreener.com/base/freysa" },
    agents: [{ name: "Freysa", platform: "Web", url: "https://www.freysa.ai/" }],
    socials: { x: "https://x.com/fraboreal_ai", website: "https://www.freysa.ai/" },
    stack: ["GPT-4", "Base L2", "Smart contracts"],
    humans: "Small team", aiAgents: 1, status: "Active", founded: "2024"
  },
  {
    name: "Luna (Virtuals)",
    desc: "Autonomous AI influencer on Virtuals Protocol. Posts independently, engages with followers, promotes the ecosystem.",
    url: "https://x.com/luna_virtuals",
    logo: "🌙",
    categories: ["Social / Influence"],
    products: ["Social accounts", "Digital content"],
    token: { ticker: "$LUNA", chain: "Base", address: "luna-virtuals", mcap: "$80M", dex: "https://dexscreener.com/base/luna-virtuals" },
    agents: [{ name: "Luna", platform: "X", url: "https://x.com/luna_virtuals" }],
    socials: { x: "https://x.com/luna_virtuals" },
    stack: ["Virtuals Protocol", "Base L2"],
    humans: 0, aiAgents: 1, status: "Active", founded: "2024"
  },
  {
    name: "Devin",
    desc: "Autonomous AI software engineer by Cognition Labs. Writes, tests, and deploys code independently. First AI employee for hire.",
    url: "https://devin.ai/",
    logo: "👨‍💻",
    categories: ["Agency / Services", "Infrastructure"],
    products: ["SaaS", "Agency / services"],
    token: null,
    agents: [{ name: "Devin", platform: "Web", url: "https://devin.ai/" }],
    socials: { x: "https://x.com/cognition_labs", website: "https://devin.ai/" },
    stack: ["Custom AI", "Cloud infrastructure"],
    humans: "Cognition team", aiAgents: 1, status: "Active", founded: "2024"
  },
  {
    name: "OpenClaw",
    desc: "Personal AI assistant platform. Agents with memory, tools, and personality running autonomously via Telegram, Discord, etc.",
    url: "https://openclaw.ai/",
    logo: "🦞",
    categories: ["Infrastructure"],
    products: ["Infrastructure", "SaaS"],
    token: null,
    agents: [],
    socials: { website: "https://openclaw.ai/", github: "https://github.com/openclaw", discord: "https://discord.com/invite/clawd" },
    stack: ["Claude", "Node.js", "Docker"],
    humans: "Small team", aiAgents: 0, status: "Active", founded: "2024"
  },
  {
    name: "CrewAI",
    desc: "Framework for orchestrating role-playing autonomous AI agents. Build multi-agent systems for complex task automation.",
    url: "https://www.crewai.com/",
    logo: "⚙️",
    categories: ["Infrastructure"],
    products: ["Infrastructure", "SaaS"],
    token: null,
    agents: [],
    socials: { x: "https://x.com/crewAIInc", website: "https://www.crewai.com/", github: "https://github.com/crewAIInc/crewAI" },
    stack: ["Python", "LangChain", "Various LLMs"],
    humans: "Team", aiAgents: 0, status: "Active", founded: "2024"
  }
];
